apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: golangapp
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
    - route:
      - destination:
          host: golangapp.prod.svc.cluster.local 
        weight: 0
      - destination:
          host: golangapp.stage.svc.cluster.local
        weight: 100


